# -*- coding: utf-8 -*-
"""COS760 Group 20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvrurNNji1QGHzzxbQc654H7G1nJCa9y

# COS760 Group 20
## Cross-lingual Semantic Relatedness for African Languages

This notebook fine-tunes AfroXLMR and XLM-R on Kinyarwanda relatedness data, evaluates zero-shot transfer to Hausa and Amharic, and analyses sentence embedding clusters for South African languages using FLORES-200 and Mafand-MT.
"""

# needs to be pinned for mafand to load properly
import subprocess, sys
subprocess.run([sys.executable, "-m", "pip", "install", "datasets<3.0.0", "-q"])

import os
from pathlib import Path
from huggingface_hub import login

# works on Colab and locally without any changes
try:
    from google.colab import userdata
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    DATA_DIR  = "/content/data"
    MODEL_DIR = "/content/models"
else:
    _ROOT     = Path(__file__).resolve().parent.parent
    DATA_DIR  = str(_ROOT / "data")
    MODEL_DIR = str(_ROOT / "models")

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

# Colab reads from Secrets or env var, locally we use .env
if IN_COLAB:
    try:
        token = os.environ.get("HF_TOKEN") or userdata.get("HF_TOKEN")
        login(token)
        print("Logged in to Hugging Face (Colab Secrets).")
    except Exception as e:
        print(f"Login failed. Set HF_TOKEN in Colab Secrets (key icon, toggle Notebook access ON): {e}")
else:
    from dotenv import load_dotenv
    load_dotenv(_ROOT / ".env")
    try:
        login(os.environ["HF_TOKEN"])
        print("Logged in to Hugging Face (.env).")
    except KeyError:
        print("HF_TOKEN not found. Add it to your .env file.")

import os
import json
import pandas as pd
from datasets import load_dataset
from tqdm import tqdm

os.makedirs(DATA_DIR, exist_ok=True)

# Languages from SemRel2024:
# kin = Kinyarwanda (Bantu-our training language)
# hau = Hausa (Afro-Asiatic Chadic-cross-family test)
# amh = Amharic (Afro-Asiatic Semitic-cross-family test)
SEMREL_LANGS = {
    "kin": "Kinyarwanda",
    "hau": "Hausa",
    "amh": "Amharic",
}

print("Loading SemRel2024")
semrel_data = {}

for code, name in SEMREL_LANGS.items():
    print(f"Loading {name}({code})")
    try:
        ds = load_dataset("SemRel/SemRel2024", code)
        rows = []
        for split_name in ["train", "dev", "test"]:
            if split_name not in ds:
                continue
            for item in ds[split_name]:
                rows.append({
                    "sentence1": item["sentence1"],
                    "sentence2": item["sentence2"],
                    "score": float(item["label"]),
                    "split": split_name,
                    "lang": code,
                })
        df = pd.DataFrame(rows)
        df.to_csv(f"{DATA_DIR}/semrel_{code}.csv", index=False)
        semrel_data[code] = df
        print(f"{len(df)} pairs saved")
    except Exception as e:
        print(f"Unable to load {name}: {e}")

# 2. FLORES-200 - unlabelled South African sentences
FLORES_LANGS = {
    "zul_Latn": "isiZulu",
    "xho_Latn": "isiXhosa",
    "nso_Latn": "Sepedi",
    "tsn_Latn": "Setswana",
    "tso_Latn": "Xitsonga",
}

print("Loading FLORES+ from HuggingFace")
flores_data = {}

for code, name in FLORES_LANGS.items():
    print(f"Loading {name} ({code})")
    try:
        ds = load_dataset("openlanguagedata/flores_plus", code)
        rows = []
        for split_name in ["dev", "devtest"]:
            if split_name not in ds:
                continue
            for item in ds[split_name]:
                rows.append({
                    "sentence": item.get("text", item.get("sentence", "")),
                    "split": split_name,
                    "lang": code,
                    "lang_name": name,
                    "domain": item.get("domain", "general"),
                })
        df = pd.DataFrame(rows)
        df.to_csv(f"{DATA_DIR}/flores_{code}.csv", index=False)
        flores_data[code] = df
        print(f"  {len(df)} sentences saved")
    except Exception as e:
        print(f"  ERROR: {e}")

# 3. Mafand-MT Dataset - unlabelled translation pairs
# Available Mafand languages: zul, xho and tsn

MAFAND_LANGS = {
    "zul": "zul",
    "xho": "xho",
    "tsn": "tsn",
}

print("\nLoading Mafand-MT")
mafand_data = {}

for code, name in MAFAND_LANGS.items():
    print(f"Loading {name}({code})")
    try:
        #Mafand pairs are always English->target language
        ds = load_dataset("masakhane/mafand", f"en-{code}")
        rows = []
        for split_name in ["train", "validation", "test"]:
            if split_name not in ds:
                continue
            for item in ds[split_name]:
                translation = item.get("translation", {})
                target_sent = translation.get(code, "")
                if target_sent:
                    rows.append({
                        "sentence": target_sent,
                        "en_sentence": translation.get("en", ""),
                        "split": split_name,
                        "lang": code,
                        "lang_name": name,
                    })
        df = pd.DataFrame(rows)

        #Let's use sample max 5000 per language to keep things manageable
        if len(df) > 5000:
            df = df.sample(5000, random_state=42).reset_index(drop=True)
        df.to_csv(f"{DATA_DIR}/mafand_{code}.csv", index=False)
        mafand_data[code] = df
        print(f"{len(df)} sentences saved")
    except Exception as e:
        print(f"Error: {e}")

print("\nDataset Summary")
print("\nSemRel2024:")
for code, df in semrel_data.items():
    train_n = len(df[df["split"] == "train"])
    dev_n = len(df[df["split"] == "dev"])
    test_n = len(df[df["split"] == "test"])
    print(f"  {SEMREL_LANGS[code]:15s} ({code})  train={train_n:4d}  dev={dev_n:4d}  test={test_n:4d}")

print("\nFLORES-200:")
for code, df in flores_data.items():
    print(f"  {FLORES_LANGS[code]:12s} ({code:10s})  sentences={len(df):4d}")

print("\nMafand-MT:")
for code, df in mafand_data.items():
    print(f"  {MAFAND_LANGS[code]:12s} ({code})  sentences={len(df):5d}")

print("\nData preparation complete. Files saved to data/")

"""# Fine-tuning
### AfroXLMR and XLM-R trained on Kinyarwanda SemRel data using mean-pooled sentence embeddings and cosine similarity regression
"""

# Fine-tune AfroXLMR (and XLM-R as baseline) on Kinyarwanda SemRel data
# Use mean-pooled sentence embeddings+cosine similarity regression
# Saves best checkpoint to models/

import os
import torch
import numpy as np
import pandas as pd
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, get_linear_schedule_with_warmup
from scipy.stats import spearmanr
from tqdm import tqdm

MODELS = {
    "afroxlmr": "Davlan/afro-xlmr-base",
    "xlmr": "FacebookAI/xlm-roberta-base",
}

TRAIN_LANG = "kin"   #Kinyarwanda
BATCH_SIZE = 8       # reduced from 16 — large model needs smaller batches to stay stable
EPOCHS     = 6
LR = {"afroxlmr": 2e-5, "xlmr": 2e-5}
MAX_LEN    = 128
DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"

os.makedirs(MODEL_DIR, exist_ok=True)
print(f"Using device: {DEVICE}")

class SemRelDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=MAX_LEN):
        self.df        = df.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_len   = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        enc1 = self.tokenizer(
            row["sentence1"],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        enc2 = self.tokenizer(
            row["sentence2"],
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )
        return {
            "input_ids1":      enc1["input_ids"].squeeze(0),
            "attention_mask1": enc1["attention_mask"].squeeze(0),
            "input_ids2":      enc2["input_ids"].squeeze(0),
            "attention_mask2": enc2["attention_mask"].squeeze(0),
            "score":           torch.tensor(row["score"], dtype=torch.float),
        }

class SentenceSimilarityModel(nn.Module):
    def __init__(self, model_name: str):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(
            model_name,
            ignore_mismatched_sizes=True
        )

    @staticmethod
    def mean_pool(token_embeddings, attention_mask):
        mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        return (token_embeddings * mask).sum(1) / mask.sum(1).clamp(min=1e-9)

    def encode(self, input_ids, attention_mask):
        out = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        emb = self.mean_pool(out.last_hidden_state, attention_mask)
        emb = torch.nan_to_num(emb, nan=0.0)
        norms = emb.norm(dim=-1, keepdim=True).clamp(min=1e-9)
        emb = emb / norms
        return emb

    def forward(self, input_ids1, attention_mask1, input_ids2, attention_mask2):
        e1  = self.encode(input_ids1, attention_mask1)
        e2  = self.encode(input_ids2, attention_mask2)
        cos = nn.functional.cosine_similarity(e1, e2)
        return (cos + 1.0) / 2.0

def train_model(model_key: str, model_name: str):
    print(f"Training {model_key.upper()}  ({model_name})")

    # Load data
    df_all   = pd.read_csv(f"{DATA_DIR}/semrel_{TRAIN_LANG}.csv")
    df_train = df_all[df_all["split"] == "train"]
    df_dev   = df_all[df_all["split"] == "dev"]
    print(f"Train: {len(df_train)}  Dev: {len(df_dev)}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = SentenceSimilarityModel(model_name).to(DEVICE)
    if model_key == "afroxlmr":
        model.encoder.gradient_checkpointing_enable()

    train_loader = DataLoader(
        SemRelDataset(df_train, tokenizer),
        batch_size=BATCH_SIZE, shuffle=True, num_workers=0   # 2→0: prevents DataLoader hangs
    )
    dev_loader = DataLoader(
        SemRelDataset(df_dev, tokenizer),
        batch_size=BATCH_SIZE, shuffle=False, num_workers=0  # 2→0: prevents DataLoader hangs
    )

    optimizer = torch.optim.AdamW(model.parameters(), lr=LR[model_key], weight_decay=0.01)
    total_steps = len(train_loader) * EPOCHS
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps
    )
    loss_fn = nn.MSELoss()

    best_rho = -2.0
    best_epoch = -1
    patience = 3
    no_improve = 0

    for epoch in range(1, EPOCHS + 1):
        # Train
        model.train()
        total_loss = 0
        for batch in tqdm(train_loader, desc=f"Epoch {epoch} [train]", leave=False):
            batch = {k: v.to(DEVICE) for k, v in batch.items()}
            preds = model(
                batch["input_ids1"], batch["attention_mask1"],
                batch["input_ids2"], batch["attention_mask2"],
            )
            loss = loss_fn(preds, batch["score"])
            if torch.isnan(loss):
                print(f"NaN batch skipped — pred range: {preds.min():.3f} to {preds.max():.3f}")
                optimizer.zero_grad()
                continue
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad()
            total_loss += loss.item()

        avg_loss = total_loss / len(train_loader)

        # Evaluate on dev
        model.eval()
        all_preds, all_labels = [], []
        with torch.no_grad():
            for batch in tqdm(dev_loader, desc=f"Epoch {epoch} [dev]", leave=False):
                batch = {k: v.to(DEVICE) for k, v in batch.items()}
                preds = model(
                    batch["input_ids1"], batch["attention_mask1"],
                    batch["input_ids2"], batch["attention_mask2"],
                )
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(batch["score"].cpu().numpy())

        rho, _ = spearmanr(all_preds, all_labels)
        if np.isnan(rho):   # constant predictions produce NaN — treat as worst case
            rho = -1.0
        print(f"  Epoch {epoch}  loss={avg_loss:.4f}  dev ρ={rho:.4f}")

        if rho > best_rho:
            best_rho   = rho
            best_epoch = epoch
            no_improve = 0
            save_path  = f"{MODEL_DIR}/{model_key}_best"
            model.encoder.save_pretrained(save_path)
            tokenizer.save_pretrained(save_path)
            print(f"New best - saved to {save_path}")
        else:
           no_improve += 1
           if no_improve >= patience:
            print(f"Early stopping at epoch {epoch}")
            break

    print(f"\n{model_key.upper()} best dev ρ = {best_rho:.4f} (epoch {best_epoch})")
    return best_rho

# Run fine-tuning — trains AfroXLMR then XLM-R on Kinyarwanda
# Checkpoints saved to models/afroxlmr_best and models/xlmr_best
ft_results = {}
for key, name in MODELS.items():
    rho = train_model(key, name)
    ft_results[key] = rho

print("\nFine-tuning complete")
for key, rho in ft_results.items():
    print(f"  {key:12s}  best dev ρ = {rho:.4f}")

"""# Zero-shot Evaluation
### Both models are tested on Hausa and Amharic with no additional training
"""

EVAL_LANGS = {
    "hau": "Hausa",
    "amh": "Amharic",
}

LANG_FAMILY = {
    "kin": "Niger-Congo / Bantu (Central)",
    "hau": "Afro-Asiatic / Chadic",
    "amh": "Afro-Asiatic / Semitic",
}

def evaluate_zeroshot(model_key: str):
    print(f"\nZero-shot evaluation — {model_key.upper()}")
    save_path = f"{MODEL_DIR}/{model_key}_best"
    tokenizer = AutoTokenizer.from_pretrained(save_path)
    model     = SentenceSimilarityModel(save_path).to(DEVICE)
    model.eval()

    results = {}
    for lang, lang_name in EVAL_LANGS.items():
        df_all  = pd.read_csv(f"{DATA_DIR}/semrel_{lang}.csv")
        df_test = df_all[df_all["split"] == "test"].reset_index(drop=True)

        loader = DataLoader(
            SemRelDataset(df_test, tokenizer),
            batch_size=BATCH_SIZE, shuffle=False, num_workers=0,
        )
        preds, labels = [], []
        with torch.no_grad():
            for batch in tqdm(loader, desc=f"  {lang}", leave=False):
                batch = {k: v.to(DEVICE) for k, v in batch.items()}
                p = model(
                    batch["input_ids1"], batch["attention_mask1"],
                    batch["input_ids2"], batch["attention_mask2"],
                )
                preds.extend(p.cpu().numpy())
                labels.extend(batch["score"].cpu().numpy())

        rho, pval = spearmanr(preds, labels)
        if np.isnan(rho):
            rho = 0.0
        results[lang] = {"rho": rho, "pval": pval, "n": len(df_test)}
        print(f"  {lang_name:12s} ({lang})  ρ={rho:.4f}  p={pval:.4f}  n={len(df_test)}")

    return results

zeroshot_results = {}
for key in MODELS:
    zeroshot_results[key] = evaluate_zeroshot(key)

print("\n=== Zero-shot Spearman ρ Results ===")
print(f"{'Language':<14} {'Family':<30} {'AfroXLMR':>10} {'XLM-R':>10}")
print("-" * 66)
for lang, lang_name in EVAL_LANGS.items():
    afro_rho = zeroshot_results["afroxlmr"][lang]["rho"]
    xlmr_rho = zeroshot_results["xlmr"][lang]["rho"]
    print(f"{lang_name:<14} {LANG_FAMILY[lang]:<30} {afro_rho:>10.4f} {xlmr_rho:>10.4f}")
print()
print(f"Training language: Kinyarwanda  [{LANG_FAMILY['kin']}]")
print("Both eval languages are cross-family — lower ρ expected.")

"""# Embedding Extraction
### South African language sentences from FLORES-200 and Mafand-MT are encoded using the trained models
"""

SA_FAMILY = {
    "zul_Latn": "isiZulu",   "xho_Latn": "isiXhosa",
    "nso_Latn": "Sepedi",    "tsn_Latn": "Setswana",
    "tso_Latn": "Xitsonga",
    "zul": "isiZulu",        "xho": "isiXhosa",
    "tsn": "Setswana",
}

def get_sentence_embeddings(sentences, tokenizer, model, batch_size=32):
    all_embs = []
    model.eval()
    for start in range(0, len(sentences), batch_size):
        batch_sents = sentences[start: start + batch_size]
        enc = tokenizer(
            batch_sents, max_length=MAX_LEN,
            padding=True, truncation=True, return_tensors="pt",
        ).to(DEVICE)
        with torch.no_grad():
            emb = model.encode(enc["input_ids"], enc["attention_mask"])
        all_embs.append(emb.cpu().numpy())
    return np.vstack(all_embs)

def extract_embeddings(dataset_name, lang_dict, model_key, max_per_lang=500):
    save_path = f"{MODEL_DIR}/{model_key}_best"
    tokenizer = AutoTokenizer.from_pretrained(save_path)
    model     = SentenceSimilarityModel(save_path).to(DEVICE)

    all_embs, all_labels = [], []
    lang_codes = list(lang_dict.keys())

    for idx, code in enumerate(lang_codes):
        csv_path = f"{DATA_DIR}/{dataset_name}_{code}.csv"
        if not os.path.exists(csv_path):
            print(f"  Skipping {code} — file not found")
            continue
        df    = pd.read_csv(csv_path)
        sents = df["sentence"].dropna().tolist()
        if len(sents) > max_per_lang:
            import random; random.seed(42)
            sents = random.sample(sents, max_per_lang)
        print(f"  {SA_FAMILY.get(code, code):12s} ({code})  {len(sents)} sentences")
        embs = get_sentence_embeddings(sents, tokenizer, model)
        all_embs.append(embs)
        all_labels.extend([idx] * len(embs))

    return np.vstack(all_embs), np.array(all_labels), lang_codes

print("Extracting FLORES embeddings...")
flores_embs_afro, flores_labels_afro, flores_codes = extract_embeddings("flores", FLORES_LANGS, "afroxlmr")
flores_embs_xlmr, flores_labels_xlmr, _            = extract_embeddings("flores", FLORES_LANGS, "xlmr")

print("\nExtracting Mafand embeddings...")
mafand_embs_afro, mafand_labels_afro, mafand_codes = extract_embeddings("mafand", MAFAND_LANGS, "afroxlmr")
mafand_embs_xlmr, mafand_labels_xlmr, _            = extract_embeddings("mafand", MAFAND_LANGS, "xlmr")
print("\nDone.")

"""# Silhouette Score Analysis
### Measures how well sentence embeddings cluster by language. Scores range from -1 to 1 where higher is better
"""

from sklearn.metrics import silhouette_score

def compute_silhouette(embs, labels, name=""):
    if len(set(labels)) < 2:
        print(f"  {name}: only 1 class — cannot compute silhouette")
        return float("nan")
    score = silhouette_score(embs, labels, metric="cosine")
    print(f"  {name:30s}  silhouette = {score:.4f}")
    return score

print("=== Silhouette Scores ===")
print("\nFLORES-200 (5 SA Bantu languages):")
sil_flores_afro = compute_silhouette(flores_embs_afro, flores_labels_afro, "AfroXLMR")
sil_flores_xlmr = compute_silhouette(flores_embs_xlmr, flores_labels_xlmr, "XLM-R")

print("\nMafand-MT (3 SA Bantu languages):")
sil_mafand_afro = compute_silhouette(mafand_embs_afro, mafand_labels_afro, "AfroXLMR")
sil_mafand_xlmr = compute_silhouette(mafand_embs_xlmr, mafand_labels_xlmr, "XLM-R")

print("\nSummary:")
print(f"  {'Dataset':<12} {'AfroXLMR':>12} {'XLM-R':>12} {'Winner':>10}")
print("  " + "-" * 48)
for ds, af, xl in [("FLORES", sil_flores_afro, sil_flores_xlmr),
                   ("Mafand",  sil_mafand_afro, sil_mafand_xlmr)]:
    winner = "AfroXLMR" if af > xl else "XLM-R"
    print(f"  {ds:<12} {af:>12.4f} {xl:>12.4f} {winner:>10}")

"""# Visualisation
### PCA plots showing sentence embedding clusters coloured by language for both models and both datasets
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn.decomposition import PCA

def plot_pca(embs, labels, lang_codes, name_map, title, ax):
    pca    = PCA(n_components=2, random_state=42, svd_solver="full")
    proj   = pca.fit_transform(embs.astype(np.float64))
    colors = cm.tab10(np.linspace(0, 1, len(lang_codes)))
    for idx, (lc, col) in enumerate(zip(lang_codes, colors)):
        mask = labels == idx
        ax.scatter(proj[mask, 0], proj[mask, 1],
                   label=name_map.get(lc, lc), color=col, s=8, alpha=0.6)
    ax.set_title(title, fontsize=11)
    ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)")
    ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)")
    ax.legend(fontsize=7, markerscale=2)
    ax.grid(True, alpha=0.3)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
plot_pca(flores_embs_afro, flores_labels_afro, flores_codes, SA_FAMILY, "FLORES — AfroXLMR", axes[0,0])
plot_pca(flores_embs_xlmr, flores_labels_xlmr, flores_codes, SA_FAMILY, "FLORES — XLM-R",   axes[0,1])
plot_pca(mafand_embs_afro, mafand_labels_afro, mafand_codes, SA_FAMILY, "Mafand — AfroXLMR", axes[1,0])
plot_pca(mafand_embs_xlmr, mafand_labels_xlmr, mafand_codes, SA_FAMILY, "Mafand — XLM-R",   axes[1,1])
fig.suptitle("Sentence Embedding Clusters by Language (PCA)", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("embedding_clusters_pca.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: embedding_clusters_pca.png")

"""# Error Analysis
### Sentence pairs where the model predictions differ most from human relatedness scores
"""

def error_analysis(model_key, lang, n=5):
    save_path = f"{MODEL_DIR}/{model_key}_best"
    tokenizer = AutoTokenizer.from_pretrained(save_path)
    model     = SentenceSimilarityModel(save_path).to(DEVICE)
    model.eval()

    df_all  = pd.read_csv(f"{DATA_DIR}/semrel_{lang}.csv")
    df_test = df_all[df_all["split"] == "test"].reset_index(drop=True)
    loader  = DataLoader(SemRelDataset(df_test, tokenizer),
                         batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
    preds = []
    with torch.no_grad():
        for batch in loader:
            batch = {k: v.to(DEVICE) for k, v in batch.items()}
            preds.extend(model(
                batch["input_ids1"], batch["attention_mask1"],
                batch["input_ids2"], batch["attention_mask2"],
            ).cpu().numpy())

    df_test["pred"]  = preds
    df_test["error"] = (df_test["pred"] - df_test["score"]).abs()

    print(f"\n--- {model_key.upper()} | {EVAL_LANGS[lang]} — top {n} errors ---")
    for _, row in df_test.nlargest(n, "error").iterrows():
        print(f"  Gold={row['score']:.2f}  Pred={row['pred']:.2f}  Err={row['error']:.2f}")
        print(f"    S1: {row['sentence1'][:80]}")
        print(f"    S2: {row['sentence2'][:80]}")
        print()

for lang in EVAL_LANGS:
    error_analysis("afroxlmr", lang)

"""# Final Results Summary"""

print("=" * 65)
print("FINAL RESULTS SUMMARY")
print("=" * 65)

print("\n1. Fine-tuning on Kinyarwanda (dev Spearman ρ)")
for key, rho in ft_results.items():
    print(f"   {key:<15}  dev ρ = {rho:.4f}")

print("\n2. Zero-shot transfer (test Spearman ρ)")
print(f"   {'Language':<12} {'AfroXLMR':>10} {'XLM-R':>10}")
print("   " + "-" * 34)
for lang, lang_name in EVAL_LANGS.items():
    af = zeroshot_results["afroxlmr"][lang]["rho"]
    xl = zeroshot_results["xlmr"][lang]["rho"]
    print(f"   {lang_name:<12} {af:>10.4f} {xl:>10.4f}")

print("\n3. SA language clustering (silhouette, cosine distance)")
print(f"   {'Dataset':<12} {'AfroXLMR':>12} {'XLM-R':>12}")
print("   " + "-" * 38)
print(f"   {'FLORES':<12} {sil_flores_afro:>12.4f} {sil_flores_xlmr:>12.4f}")
print(f"   {'Mafand':<12} {sil_mafand_afro:>12.4f} {sil_mafand_xlmr:>12.4f}")
print("=" * 65)
